### ISSUE TITLE
Issue about import _pyfreenect

### ISSUE THREAD

**Issue by RunningStone** [remexre/pyfreenect2#6]
Problem is:

> > Traceback (most recent call last):
> >   File "/Users/name/Documents/KinectDriver/pyfreenect2/pyfreenect2.py", line 1, in <module>
> >     import _pyfreenect2
> >   File "build/bdist.macosx-10.5-x86_64/egg/_pyfreenect2.py", line 7, in <module>
> >   File "build/bdist.macosx-10.5-x86_64/egg/_pyfreenect2.py", line 6, in __bootstrap__
> > ImportError: dlopen(/Users/name/.python-eggs/pyfreenect2-0.0.0-py2.7-macosx-10.5-x86_64.egg-tmp/_pyfreenect2.so, 2): Symbol not found: __ZN12libfreenect222SyncMultiFrameListener15waitForNewFrameERSt3mapINS_5Frame4TypeEPS2_St4lessIS3_ESaISt4pairIKS3_S4_EEE
> >   Referenced from: /Users/name/.python-eggs/pyfreenect2-0.0.0-py2.7-macosx-10.5-x86_64.egg-tmp/_pyfreenect2.so
> >   Expected in: dynamic lookup

The hardware is MacBook Pro（15-inch, 2012) OS X 10.11.2
The libfreenect2 works well. at Users/name/Documents/KinectDriver/libfreenect2
                                              Dynamic lib at: Users/name/Documents/KinectDriver/libfreenect2/build/lib
python work's well. at /Users/name/anaconda/bin/python

I have edited the setup file to make it work.

> > ```
> >    extra_compile_args = ["-fpermissive",
> >                           "-I/Users/name/Documents/KinectDriver/libfreenect2/include",
> >                           "-I/Users/name/Documents/KinectDriver/libfreenect2/build/libfreenect2"
> >                             ],
> > include_dirs=[numpy.get_include()],
> > define_macros=[("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")],
> > library_dirs=["/Users/name/Documents/KinectDriver/libfreenect2/build/lib"]
> > ```

I also try to use some tool to locate the problem(by using otool and nm), but.....

> > otool -L /Users/panshi/.python-eggs/pyfreenect2-0.0.0-py2.7-macosx-10.5-x86_64.egg-tmp/_pyfreenect2.so
> > output is:
> > /Users/name/.python-eggs/pyfreenect2-0.0.0-py2.7-macosx-10.5-x86_64.egg-tmp/_pyfreenect2.so:
> >     /Users/name/Documents/KinectDriver/libfreenect2/build/lib/libfreenect2.0.1.dylib (compatibility version 0.1.0, current version 0.1.0)
> >     /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
> >     /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
> >     /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 913.0.0)
> > nm /Users/name/.python-eggs/pyfreenect2-0.0.0-py2.7-macosx-10.5-x86_64.egg-tmp/_pyfreenect2.so
> > nm output as
> > 0000000000003628 s GCC_except_table0
> > 00000000000036bc s GCC_except_table0
> > 00000000000036e8 s GCC_except_table1
> > 0000000000003714 s GCC_except_table1
> > 00000000000035fc s GCC_except_table2
> > 0000000000003664 s GCC_except_table6
> > 0000000000003690 s GCC_except_table7
> >                  U _PyArg_ParseTuple
> >                  U _PyCObject_AsVoidPtr
> >                  U _PyCObject_Type
> >                  U _PyCapsule_GetPointer
> >                  U _PyCapsule_New
> >                  U _PyErr_Format
> >                  U _PyErr_Print
> >                  U _PyErr_SetString
> >                  U _PyExc_AttributeError
> >                  U _PyExc_ImportError
> >                  U _PyExc_RuntimeError
> >                  U _PyImport_ImportModule
> >                  U _PyInt_FromLong
> >                  U _PyInt_FromSize_t
> >                  U _PyObject_GetAttrString
> >                  U _PyString_FromString
> >                  U _Py_InitModule4_64
> > 0000000000001e20 t __GLOBAL__sub_I_Frame.cpp
> > 00000000000023c0 t __GLOBAL__sub_I_Freenect2.cpp
> > 0000000000002a80 t __GLOBAL__sub_I_Freenect2Device.cpp
> > 0000000000002e60 t __GLOBAL__sub_I_SyncMultiFrameListener.cpp
> > 0000000000001940 t __GLOBAL__sub_I_pyfreenect2.cpp
> >                  U __Py_NoneStruct
> >                  U __Py_NotImplementedStruct
> >                  U __Unwind_Resume
> > 00000000000044a8 b __Z11PyArray_API
> > 0000000000004498 b __Z11PyArray_API
> > 0000000000001b60 t __Z13_import_arrayv
> > 0000000000001770 t __Z13_import_arrayv
> > 0000000000001980 T __Z16py_Frame_destroyP7_object
> > 0000000000001a70 T __Z16py_Frame_getDataP7_objectS0_
> > 0000000000001a10 T __Z17py_Frame_getWidthP7_objectS0_
> > 00000000000022c0 T __Z18getGlobalFreenect2v
> > 00000000000019b0 T __Z18py_Frame_getHeightP7_objectS0_
> > 00000000000022d0 T __Z18py_numberOfDevicesP7_objectS0_
> > 0000000000001e60 T __Z19py_FrameMap_destroyP7_object
> > 0000000000002ac0 T __Z19py_Registration_newP7_objectS0_
> > 0000000000001ea0 T __Z20py_FrameMap_getFrameP7_objectS0_
> > 0000000000001d30 T __Z21py_Frame_getDepthDataP7_objectS0_
> > 0000000000002c50 T __Z21py_Registration_applyP7_objectS0_
> > 0000000000002400 T __Z22py_Freenect2Device_newP7_objectS0_
> > 0000000000002570 T __Z23py_Freenect2Device_stopP7_objectS0_
> > 0000000000002c00 T __Z23py_Registration_destroyP7_object
> > 0000000000002510 T __Z24py_Freenect2Device_startP7_objectS0_
> > 00000000000024f0 T __Z26py_Freenect2Device_destroyP7_object
> > 0000000000002cc0 T __Z29py_SyncMultiFrameListener_newP7_objectS0_
> > 0000000000002310 T __Z31py_getDefaultDeviceSerialNumberP7_objectS0_
> > 0000000000002c90 T __Z33py_SyncMultiFrameListener_destroyP7_object
> > 00000000000027e0 T __Z34py_Freenect2Device_getSerialNumberP7_objectS0_
> > 00000000000029f0 T __Z36py_Freenect2Device_getIRCameraParamsP7_objectS0_
> > 00000000000028a0 T __Z37py_Freenect2Device_getFirmwareVersionP7_objectS0_
> > 0000000000002960 T __Z39py_Freenect2Device_getColorCameraParamsP7_objectS0_
> > 00000000000025d0 T __Z40py_Freenect2Device_setColorFrameListenerP7_objectS0_
> > 0000000000002a60 T __Z41py_Freenect2Device_IRCameraParams_destroyP7_object
> > 0000000000002da0 T __Z41py_SyncMultiFrameListener_waitForNewFrameP7_objectS0_
> > 00000000000029d0 T __Z44py_Freenect2Device_ColorCameraParams_destroyP7_object
> > 0000000000002750 T __Z45py_Freenect2Device_setIrAndDepthFrameListenerP7_objectS0_
> > 00000000000041e0 d __ZL18pyfreenect2Methods
> >                  U __ZN12libfreenect212RegistrationC1ENS_15Freenect2Device14IrCameraParamsENS1_17ColorCameraParamsE
> >                  U __ZN12libfreenect212RegistrationD1Ev
> >                  U __ZN12libfreenect222SyncMultiFrameListener15waitForNewFrameERSt3mapINS_5Frame4TypeEPS2_St4lessIS3_ESaISt4pairIKS3_S4_EEE
> >                  U __ZN12libfreenect222SyncMultiFrameListenerC1Ej
> >                  U __ZN12libfreenect29Freenect210openDeviceERKSs
> >                  U __ZN12libfreenect29Freenect216enumerateDevicesEv
> >                  U __ZN12libfreenect29Freenect228getDefaultDeviceSerialNumberEv
> >                  U __ZN12libfreenect29Freenect2C1EPv
> >                  U __ZN12libfreenect29Freenect2D1Ev
> >                  U __ZNKSt9basic_iosIcSt11char_traitsIcEE5widenEc
> >                  U __ZNSo3putEc
> >                  U __ZNSo5flushEv
> >                  U __ZNSolsEPKv
> >                  U __ZNSs4_Rep10_M_destroyERKSaIcE
> >                  U __ZNSs4_Rep20_S_empty_rep_storageE
> >                  U __ZNSsC1EPKcRKSaIcE
> > 00000000000021e0 T __ZNSt8_Rb_treeIN12libfreenect25Frame4TypeESt4pairIKS2_PS1_ESt10_Select1stIS6_ESt4lessIS2_ESaIS6_EE16_M_insert_uniqueERKS6_
> > 0000000000001fe0 T __ZNSt8_Rb_treeIN12libfreenect25Frame4TypeESt4pairIKS2_PS1_ESt10_Select1stIS6_ESt4lessIS2_ESaIS6_EE16_M_insert_uniqueESt17_Rb_tree_iteratorIS6_ERKS6_
> > 0000000000001f90 T __ZNSt8_Rb_treeIN12libfreenect25Frame4TypeESt4pairIKS2_PS1_ESt10_Select1stIS6_ESt4lessIS2_ESaIS6_EE8_M_eraseEPSt13_Rb_tree_nodeIS6_E
> >                  U __ZNSt8ios_base4InitC1Ev
> >                  U __ZNSt8ios_base4InitD1Ev
> >                  U __ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l
> >                  U __ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
> >                  U __ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base
> >                  U __ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_
> >                  U __ZSt4cout
> > 00000000000044b1 b __ZStL8__ioinit
> > 00000000000044b0 b __ZStL8__ioinit
> > 00000000000044a0 b __ZStL8__ioinit
> > 0000000000004490 b __ZStL8__ioinit
> >                  U __ZdlPv
> >                  U __Znwm
> >                  U ___cxa_atexit
> >                  U ___gxx_personality_v0
> >                  U ___stack_chk_fail
> >                  U ___stack_chk_guard
> > 00000000000016e4 t __dyld_func_lookup
> > 0000000000004480 S _freenect2
> > 00000000000016f0 T _init_pyfreenect2
> >                  U _puts
> > 00000000000016d0 t dyld_stub_binding_helper

**Comment by GitKraug** [comment]
Is this solved?? Have the same issue myself!
