### ISSUE TITLE
_pyfreenect2.so: undefined symbol: _ZN12libfreenect29Freenect2D1Ev

### ISSUE THREAD

**Issue by m1lhaus** [remexre/pyfreenect2#9]
Today I downloaded and built fresh libfreenect2 and this Python wrapper. I managed to compile and install libraries (libfreenect2 works). To install pyfreenect I had to modify setup.py like this:

```
libfreenect2_module = Extension("_pyfreenect2",
    libraries=["/home/milan/Programy/libfreenect2/install/lib/libfreenect2.so"],
    sources=["pyfreenect2.cpp",
        "src/Frame.cpp",
        "src/FrameMap.cpp",
        "src/Freenect2.cpp",
        "src/Freenect2Device.cpp",
        "src/Registration.cpp",
        "src/SyncMultiFrameListener.cpp"],
        extra_compile_args = ["-fpermissive"],
    include_dirs=[numpy.get_include(), "/home/milan/Programy/libfreenect2/install/include"],
    define_macros=[("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")])
```

But when I want run pyfreenect2, I am getting this error:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import pyfreenect2
  File "/home/milan/Stažené/pyfreenect2-master/pyfreenect2.py", line 1, in <module>
    import _pyfreenect2
  File "build/bdist.linux-x86_64/egg/_pyfreenect2.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_pyfreenect2.py", line 6, in __bootstrap__
ImportError: /home/milan/.python-eggs/pyfreenect2-0.0.0-py2.7-linux-x86_64.egg-tmp/_pyfreenect2.so: undefined symbol: _ZN12libfreenect29Freenect2D1Ev
```

Any ideas? Thanks

**Comment by GitKraug** [comment]
Any results on this??? Have the same problem myself!

**Comment by AStorus** [comment]
Where did the installer write your libfreenect2.so file to? Or does the installer instead only write out a libfreenect2-0.0.0-py2.7.linux-x86_64.egg file?

**Comment by Myzhencai** [comment]
@m1lhaus ,I have the similar problem as you .Have you solved the issue?
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/gaofei/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import pyfreenect2
  File "/home/gaofei/pyfreenect2/pyfreenect2.py", line 1, in <module>
    import _pyfreenect2
  File "build/bdist.linux-x86_64/egg/_pyfreenect2.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_pyfreenect2.py", line 6, in __bootstrap__
ImportError: /home/gaofei/.python-eggs/pyfreenect2-0.0.0-py2.7-linux-x86_64.egg-tmp/_pyfreenect2.so: undefined symbol: _Z25getSPFrameMapFromFrameMapPSt3mapIN12libfreenect25Frame4TypeEPS1_St4lessIS2_ESaISt4pairIKS2_S3_EEE

**Comment by m1lhaus** [comment]
@Myzhencai No, I ended up using C++ library. But from error name, I would recommend you check you _pyfreenect2.so library for getSPFrameMapFromFrameMap symbol name (just use whatever highperformace text editor you have - not gedit :D). Maybe method fingerprint changed or wrong binary version you are using.

**Comment by Myzhencai** [comment]
@m1lhaus I will try it ,many thanks .Have a nice day
